name: Snyk Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
jobs:
  deps_scan:
    name: Scan dependencias (Node.js)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Snyk y snyk-to-html
        run: |
          npm i -g snyk snyk-to-html

      - name: Autenticación Snyk
        run: snyk auth "${SNYK_TOKEN}"

      - name: Instalar deps
        run: |
          if [ -f package.json ]; then npm ci --ignore-scripts; fi

      - name: Snyk test (JSON y SARIF)
        run: |
          snyk test --all-projects --json > snyk.json || true

      - name: Convertir a HTML
        run: snyk-to-html -i snyk.json -o snyk-report.html

      - name: Subir artifact (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report-deps
          path: snyk-report.html
          if-no-files-found: warn
          retention-days: 7

  iac_scan:
    name: Scan IaC (Terraform/K8s)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Snyk y snyk-to-html
        run: |
          npm i -g snyk snyk-to-html

      - name: Autenticación Snyk
        run: snyk auth "${SNYK_TOKEN}"

      - name: Snyk IaC
        run: |
          snyk iac test --report --json > snyk-iac.json || true

      - name: Convertir a HTML
        run: snyk-to-html -i snyk-iac.json -o snyk-iac-report.html

      - name: Subir artifact (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report-iac
          path: snyk-iac-report.html
          retention-days: 7
